name: Github Actions Maven Build Example

on:
 push:
    branches: [ main ]
    tags:
      - '*'
 pull_request:
 workflow_dispatch:

jobs:
  build:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
    - name: STEP-1  - Checkout main branch from Github
      uses: actions/checkout@v3
    
    - name: STEP-2  - Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8   
        distribution: 'zulu'
        
    - name: STEP-3  - Set up a cache for Maven
      uses: actions/cache@v3
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2       
       
    - name: STEP-4 - Build with Maven
      run: mvn clean install

    - name: STEP-5 - JUNIT Test with Maven
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

    - name: STEP-6 - Publish Test Report
      uses: kumvijaya/junit-report@main
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'   # Path to test results
        check_name: Example JUnit Test Report
        include_passed: true
        detailed_summary: true
        summary: '<table><thead><tr><th> Application (src/applications) </th></tr></thead><tbody><tr><td> test </td></tr></tbody></table>'
        check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'
        annotate_only: ${{ github.event_name == 'workflow_dispatch' }}